<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.tokenrealty</groupId>
    <artifactId>tokenrealty-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>TokenRealty Platform</name>
    <description>TokenRealty monorepo parent</description>

    <modules>
        <module>tokenrealty-security</module>
        <module>token-realty-app</module>
        <module>token-issuance-service</module>
        <module>auth-service</module>
        <module>marketplace-service</module>
    </modules>

    <properties>
        <java.version>21</java.version>
        <tokenrealty-security.version>0.0.1-SNAPSHOT</tokenrealty-security.version>
    </properties>
</project>
