/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/compliance": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listCompliance"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/compliance/{id}/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["verifyCompliance"];
    trace?: never;
  };
  "/v1/compliance/document-reviews/pending": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listPendingDocumentReviews"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/compliance/document-reviews/{documentId}/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["verifyDocumentReview"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CompliancePage: {
      content?: components["schemas"]["ComplianceRecord"][];
      totalElements?: number;
    };
    ComplianceVerifyRequest: {
      /** Format: date-time */
      kycExpiresAt: string;
    };
    ComplianceRecord: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      investorId?: string;
      walletAddress?: string;
      fullName?: string;
      countryCode?: string;
      status?: string;
    };
    DocumentReview: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      documentId?: string;
      /** Format: uuid */
      buildingId?: string;
      /** Format: uuid */
      flatId?: string | null;
      documentType?: string;
      ipfsCid?: string;
      status?: string;
      isVerified?: boolean;
      /** Format: date-time */
      uploadedAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listCompliance: {
    parameters: {
      query?: {
        status?: "PENDING" | "APPROVED" | "REJECTED" | "EXPIRED" | "REVOKED";
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CompliancePage"];
        };
      };
    };
  };
  verifyCompliance: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ComplianceVerifyRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ComplianceRecord"];
        };
      };
    };
  };
  listPendingDocumentReviews: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentReview"][];
        };
      };
    };
  };
  verifyDocumentReview: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        documentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentReview"];
        };
      };
    };
  };
}
