/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/documents/{documentId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getDocument"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/documents/upload": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["uploadDocument"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Document: {
      /** Format: uuid */
      id?: string;
      documentName?: string;
      documentType?: string;
      ipfsCid?: string | null;
      storageUrl?: string | null;
      fileSizeBytes?: number | null;
      mimeType?: string | null;
      isVerified?: boolean;
      /** Format: date-time */
      createdAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getDocument: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        documentId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Document"];
        };
      };
    };
  };
  uploadDocument: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": {
          /** Format: binary */
          file: string;
          documentName: string;
          /** @enum {string} */
          documentType:
            | "TITLE_DEED"
            | "FLOOR_PLAN"
            | "BUILDING_PERMIT"
            | "INSPECTION_REPORT"
            | "VALUATION_REPORT"
            | "SPV_REGISTRATION"
            | "ARTICLES_OF_INCORPORATION"
            | "ENVIRONMENTAL_AUDIT"
            | "KYC_DOCUMENT"
            | "LEASE_AGREEMENT"
            | "INSURANCE_POLICY"
            | "OTHER";
          /** Format: uuid */
          buildingId?: string;
          /** Format: uuid */
          flatId?: string;
        };
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Document"];
        };
      };
    };
  };
}
