/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/bff/flats/{flatId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getBffFlatDetail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/bff/listings/{listingId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getBffListingDetail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/bff/buildings/{buildingId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getBffBuildingDetail"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/bff/investors/{investorId}/portfolio": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getBffPortfolio"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/bff/tenants/{tenantId}/lease": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getBffTenantLeases"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/bff/tenants/{tenantId}/maintenance": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getBffTenantMaintenance"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/bff/orders/{orderId}/status-stream": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["streamOrderStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    TokenContractSummary: {
      /** Format: uuid */
      contractId?: string;
      contractAddress?: string;
      tokenSymbol?: string;
      /** Format: int64 */
      totalSupply?: number;
      tokenPriceUsd?: number;
      status?: string;
    };
    ListingSummary: {
      /** Format: uuid */
      listingId?: string;
      listingType?: string;
      status?: string;
      priceUsd?: number;
      /** Format: int64 */
      tokensAvailable?: number;
      /** Format: int64 */
      tokensTotal?: number;
      /** Format: int64 */
      minInvestmentTokens?: number;
      title?: string;
    };
    FlatDetailResponse: {
      /** Format: uuid */
      flatId?: string;
      /** Format: uuid */
      buildingId?: string;
      buildingName?: string;
      flatNumber?: string;
      floor?: number;
      areaSqm?: number;
      status?: string;
      tokenContract?: components["schemas"]["TokenContractSummary"];
      listing?: components["schemas"]["ListingSummary"];
    };
    ListingDetailResponse: {
      listing?: components["schemas"]["ListingSummary"];
      /** Format: uuid */
      flatId?: string;
      buildingName?: string;
      flatNumber?: string;
      flatStatus?: string;
      tokenContract?: components["schemas"]["TokenContractSummary"];
    };
    EnrichedTokenHoldingView: {
      /** Format: uuid */
      contractId?: string;
      /** Format: uuid */
      flatId?: string;
      tokenSymbol?: string;
      walletAddress?: string;
      /** Format: int64 */
      balance?: number;
      tokenPriceUsd?: number;
    };
    PortfolioBalanceView: {
      /** Format: uuid */
      investorId?: string;
      primaryWalletAddress?: string;
      tokenHoldings?: components["schemas"]["EnrichedTokenHoldingView"][];
    };
    PortfolioBffResponse: {
      balance?: components["schemas"]["PortfolioBalanceView"];
    };
    BuildingBffDetailResponse: {
      tokenizedFlatCount?: number;
      availableFlatCount?: number;
    };
    OrderStatusEvent: {
      /** Format: uuid */
      orderId?: string;
      orderStatus?: string;
      tradeStatus?: string;
    };
    TenantLeaseView: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      flatId?: string;
      /** Format: uuid */
      tenantId?: string;
      tenantWallet?: string;
      /** Format: uuid */
      spvRecipientId?: string;
      spvWallet?: string;
      monthlyRentUsd?: number;
      /** Format: date */
      startDate?: string;
      /** Format: date */
      endDate?: string;
      status?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    TenantFlatSummary: {
      /** Format: uuid */
      flatId?: string;
      /** Format: uuid */
      buildingId?: string;
      buildingName?: string;
      flatNumber?: string;
      floor?: number;
      areaSqm?: number;
      status?: string;
    };
    TenantLeaseBffResponse: {
      lease?: components["schemas"]["TenantLeaseView"];
      flat?: components["schemas"]["TenantFlatSummary"];
      rentDue?: boolean;
    };
    MaintenanceTicketView: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      leaseId?: string;
      /** Format: uuid */
      flatId?: string;
      /** Format: uuid */
      tenantId?: string;
      title?: string;
      description?: string;
      /** @enum {string} */
      status?: "OPEN" | "RESOLVED";
      /** Format: date-time */
      createdAt?: string;
    };
    TenantMaintenanceBffResponse: {
      lease?: components["schemas"]["TenantLeaseView"];
      flat?: components["schemas"]["TenantFlatSummary"];
      openTickets?: components["schemas"]["MaintenanceTicketView"][];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getBffFlatDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        flatId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FlatDetailResponse"];
        };
      };
    };
  };
  getBffListingDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        listingId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingDetailResponse"];
        };
      };
    };
  };
  getBffBuildingDetail: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        buildingId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BuildingBffDetailResponse"];
        };
      };
    };
  };
  getBffPortfolio: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investorId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PortfolioBffResponse"];
        };
      };
    };
  };
  getBffTenantLeases: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tenantId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TenantLeaseBffResponse"][];
        };
      };
    };
  };
  getBffTenantMaintenance: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        tenantId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TenantMaintenanceBffResponse"][];
        };
      };
    };
  };
  streamOrderStatus: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        orderId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Server-sent events stream of order status updates */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/event-stream": components["schemas"]["OrderStatusEvent"];
        };
      };
    };
  };
}
