/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/indexer/status": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getIndexerStatus"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/indexer/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listIndexedEvents"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/indexer/reconciliation": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listReconciliationMismatches"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/indexer/reconciliation/{mismatchId}/remediate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["remediateReconciliationMismatch"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    IndexerStatusResponse: {
      cursorId?: string;
      /** Format: int64 */
      lastBlockNumber?: number;
    };
    IndexedEvent: {
      /** Format: uuid */
      id?: string;
      eventType?: string;
      contractAddress?: string;
      txHash?: string;
      logIndex?: number;
      /** Format: int64 */
      blockNumber?: number;
      payload?: string;
      /** Format: date-time */
      createdAt?: string;
    };
    IndexedEventPage: {
      content?: components["schemas"]["IndexedEvent"][];
      /** Format: int64 */
      totalElements?: number;
      totalPages?: number;
      size?: number;
      number?: number;
    };
    ReconciliationMismatch: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      contractId?: string;
      contractAddress?: string;
      walletAddress?: string;
      /** Format: int64 */
      dbBalance?: number;
      /** Format: int64 */
      chainBalance?: number;
      resolved?: boolean;
      /** Format: date-time */
      createdAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getIndexerStatus: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IndexerStatusResponse"];
        };
      };
    };
  };
  listIndexedEvents: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IndexedEventPage"];
        };
      };
    };
  };
  listReconciliationMismatches: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReconciliationMismatch"][];
        };
      };
    };
  };
  remediateReconciliationMismatch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        mismatchId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReconciliationMismatch"];
        };
      };
    };
  };
}
