/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listTokens"];
    put?: never;
    post: operations["issueTokens"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tokens/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getToken"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tokens/by-flat/{flatId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getTokenByFlat"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/investors/{investorId}/holdings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listInvestorHoldings"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    TokenContractPage: {
      content?: components["schemas"]["TokenContract"][];
      totalElements?: number;
    };
    IssueTokenRequest: {
      /** Format: uuid */
      flatId: string;
      /** Format: uuid */
      buildingId: string;
      tokenName: string;
      tokenSymbol: string;
      totalSupply: number;
      tokenPriceUsd: number;
      spvWalletAddress: string;
    };
    TokenContract: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      flatId?: string;
      /** Format: uuid */
      buildingId?: string;
      tokenName?: string;
      tokenSymbol?: string;
      totalSupply?: number;
      tokenPriceUsd?: number;
      contractAddress?: string | null;
      status?: string;
      spvWalletAddress?: string;
    };
    TokenHolding: {
      /** Format: uuid */
      contractId?: string;
      /** Format: uuid */
      flatId?: string;
      tokenSymbol?: string;
      balance?: number;
      balanceUsd?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listTokens: {
    parameters: {
      query?: {
        activeOnly?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenContractPage"];
        };
      };
    };
  };
  issueTokens: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["IssueTokenRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenContract"];
        };
      };
    };
  };
  getToken: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenContract"];
        };
      };
    };
  };
  getTokenByFlat: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        flatId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenContract"];
        };
      };
    };
  };
  listInvestorHoldings: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investorId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenHolding"][];
        };
      };
    };
  };
}
