/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/listings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listListings"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/orders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listOrders"];
    put?: never;
    post: operations["placeOrder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/orders/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getOrder"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/orders/{id}/trade": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getOrderTrade"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/orders/sell": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["placeSellOrder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/orders/{id}/settle": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["settleOrder"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    ListingPage: {
      content?: components["schemas"]["Listing"][];
      totalElements?: number;
    };
    Listing: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      flatId?: string;
      status?: string;
      priceUsd?: number;
      tokensAvailable?: number;
      title?: string;
    };
    PlaceOrderRequest: {
      /** Format: uuid */
      listingId: string;
      /** Format: uuid */
      buyerId: string;
      buyerWallet: string;
      tokenAmount: number;
    };
    OrderPage: {
      content?: components["schemas"]["Order"][];
    };
    Order: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      listingId?: string;
      status?: string;
      /** Format: uuid */
      buyerId?: string;
      tokenAmount?: number;
      totalPriceUsd?: number;
    };
    Trade: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      orderId?: string;
      status?: string;
      /** Format: uuid */
      paymentId?: string;
      /** Format: uuid */
      transferId?: string;
    };
    PlaceSellOrderRequest: {
      /** Format: uuid */
      flatId: string;
      /** Format: uuid */
      contractId: string;
      /** Format: uuid */
      sellerInvestorId: string;
      sellerWallet: string;
      priceUsd: number;
      tokenAmount: number;
      title?: string;
      description?: string;
    };
    SettleTradeRequest: {
      /** Format: uuid */
      paymentId: string;
      /** Format: uuid */
      transferId: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listListings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ListingPage"];
        };
      };
    };
  };
  listOrders: {
    parameters: {
      query?: {
        buyerId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderPage"];
        };
      };
    };
  };
  placeOrder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaceOrderRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Order"];
        };
      };
    };
  };
  getOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Order"];
        };
      };
    };
  };
  getOrderTrade: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Trade"];
        };
      };
    };
  };
  placeSellOrder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PlaceSellOrderRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Order"];
        };
      };
    };
  };
  settleOrder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SettleTradeRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Trade"];
        };
      };
    };
  };
}
