/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/notifications/preferences/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getNotificationPreferences"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["updateNotificationPreferences"];
    trace?: never;
  };
  "/v1/notifications/send": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["sendNotification"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    NotificationPreferences: {
      /** Format: uuid */
      userId?: string;
      emailEnabled?: boolean;
      tradeAlerts?: boolean;
      dividendAlerts?: boolean;
      rentReminders?: boolean;
    };
    UpdateNotificationPreferencesRequest: {
      emailEnabled: boolean;
      tradeAlerts: boolean;
      dividendAlerts: boolean;
      rentReminders: boolean;
    };
    SendNotificationRequest: {
      eventType: string;
      payload: Record<string, never>;
    };
    SendNotificationResponse: {
      eventType?: string;
      status?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getNotificationPreferences: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotificationPreferences"];
        };
      };
    };
  };
  updateNotificationPreferences: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        userId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateNotificationPreferencesRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NotificationPreferences"];
        };
      };
    };
  };
  sendNotification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendNotificationRequest"];
      };
    };
    responses: {
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SendNotificationResponse"];
        };
      };
    };
  };
}
