/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/payments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listPayments"];
    put?: never;
    post: operations["initiatePayment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/payments/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getPayment"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/payments/{id}/confirm": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["confirmPayment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/payments/{id}/release": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["releaseEscrow"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    PaymentPage: {
      content?: components["schemas"]["Payment"][];
      totalElements?: number;
    };
    InitiatePaymentRequest: {
      /** Format: uuid */
      orderId: string;
      /** Format: uuid */
      payerId: string;
      payerWallet: string;
      amount: number;
      /** @enum {string} */
      currency: "USDC" | "USD" | "MATIC" | "ETH";
      paymentType?: string;
      /** Format: uuid */
      sellerRecipientId?: string | null;
    };
    ConfirmPaymentRequest: {
      txHash: string;
    };
    Payment: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      orderId?: string;
      /** Format: uuid */
      payerId?: string;
      payerWallet?: string;
      amount?: number;
      currency?: string;
      /** @enum {string} */
      status?: "PENDING" | "CONFIRMED" | "RELEASED" | "REFUNDED" | "FAILED";
      txHash?: string | null;
      escrow?: components["schemas"]["Escrow"];
    };
    Escrow: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      paymentId?: string;
      /** Format: uuid */
      orderId?: string;
      amount?: number;
      currency?: string;
      /** @enum {string} */
      status?: "AWAITING" | "HELD" | "RELEASED" | "REFUNDED";
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listPayments: {
    parameters: {
      query?: {
        payerId?: string;
        orderId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentPage"];
        };
      };
    };
  };
  initiatePayment: {
    parameters: {
      query?: never;
      header: {
        "Idempotency-Key": string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["InitiatePaymentRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Payment"];
        };
      };
    };
  };
  getPayment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Payment"];
        };
      };
    };
  };
  confirmPayment: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ConfirmPaymentRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Payment"];
        };
      };
    };
  };
  releaseEscrow: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Payment"];
        };
      };
    };
  };
}
