/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/buildings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listBuildings"];
    put?: never;
    post: operations["createBuilding"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/buildings/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getBuilding"];
    put: operations["updateBuilding"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/buildings/{buildingId}/flats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listFlatsByBuilding"];
    put?: never;
    post: operations["createFlat"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/flats/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getFlat"];
    put: operations["updateFlat"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    BuildingPage: {
      content?: components["schemas"]["BuildingResponse"][];
      totalElements?: number;
    };
    BuildingResponse: {
      /** Format: uuid */
      id?: string;
      name?: string;
      address?: string;
      city?: string;
      country?: string;
      status?: string;
      flatCount?: number;
      propertyCategory?: string;
    };
    BuildingDetailResponse: components["schemas"]["BuildingResponse"] & {
      postalCode?: string;
      totalFloors?: number;
      totalFlats?: number;
      constructionYear?: number;
      totalAreaSqm?: number;
      cadastralReference?: string;
      flats?: components["schemas"]["FlatSummary"][];
      spv?: components["schemas"]["SpvSummary"];
    };
    CreateBuildingRequest: {
      name: string;
      address: string;
      city: string;
      country: string;
      postalCode?: string;
      totalFloors?: number;
      totalFlats?: number;
      constructionYear?: number;
      totalAreaSqm?: number;
      propertyCategory?: string;
      cadastralReference?: string;
    };
    UpdateBuildingRequest: {
      name?: string;
      address?: string;
      city?: string;
      country?: string;
      postalCode?: string;
      totalFloors?: number;
      totalAreaSqm?: number;
      propertyCategory?: string;
      cadastralReference?: string;
    };
    FlatPage: {
      content?: components["schemas"]["FlatResponse"][];
      totalElements?: number;
    };
    FlatSummary: {
      /** Format: uuid */
      id?: string;
      flatNumber?: string;
      floor?: number;
      areaSqm?: number;
      status?: string;
      tokenPriceUsd?: number;
    };
    FlatResponse: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      buildingId?: string;
      buildingName?: string;
      flatNumber?: string;
      floor?: number;
      areaSqm?: number;
      netUsableAreaSqm?: number;
      cadastralReference?: string;
      numRooms?: number;
      numBathrooms?: number;
      status?: string;
      tokenContractAddress?: string;
      totalTokens?: number;
      tokenPriceUsd?: number;
    };
    CreateFlatRequest: {
      flatNumber: string;
      floor: number;
      areaSqm: number;
      numRooms: number;
      numBathrooms: number;
      cadastralReference?: string;
      netUsableAreaSqm?: number;
    };
    UpdateFlatRequest: {
      flatNumber?: string;
      floor?: number;
      areaSqm?: number;
      numRooms?: number;
      numBathrooms?: number;
      cadastralReference?: string;
      netUsableAreaSqm?: number;
    };
    SpvSummary: {
      /** Format: uuid */
      id?: string;
      legalName?: string;
      registrationNumber?: string;
      kycVerified?: boolean;
      status?: string;
      walletAddress?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listBuildings: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BuildingPage"];
        };
      };
    };
  };
  createBuilding: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBuildingRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BuildingResponse"];
        };
      };
    };
  };
  getBuilding: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BuildingDetailResponse"];
        };
      };
    };
  };
  updateBuilding: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateBuildingRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BuildingResponse"];
        };
      };
    };
  };
  listFlatsByBuilding: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        buildingId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FlatPage"];
        };
      };
    };
  };
  createFlat: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        buildingId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateFlatRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FlatResponse"];
        };
      };
    };
  };
  getFlat: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FlatResponse"];
        };
      };
    };
  };
  updateFlat: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateFlatRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["FlatResponse"];
        };
      };
    };
  };
}
