/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/leases": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listLeases"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/leases/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getLease"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/rent-payments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listRentPayments"];
    put?: never;
    post: operations["recordRentPayment"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/maintenance-tickets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listMaintenanceTickets"];
    put?: never;
    post: operations["createMaintenanceTicket"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/maintenance-tickets/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getMaintenanceTicket"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch: operations["updateMaintenanceTicket"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Lease: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      flatId?: string;
      /** Format: uuid */
      tenantId?: string;
      tenantWallet?: string;
      monthlyRentUsd?: number;
      /** Format: date */
      startDate?: string;
      /** Format: date */
      endDate?: string;
      status?: string;
    };
    RecordRentPaymentRequest: {
      /** Format: uuid */
      leaseId: string;
      period: string;
      amount: number;
    };
    RentPayment: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      leaseId?: string;
      period?: string;
      amount?: number;
      status?: string;
      /** Format: date-time */
      paidAt?: string;
    };
    CreateMaintenanceTicketRequest: {
      /** Format: uuid */
      leaseId: string;
      title: string;
      description: string;
    };
    UpdateMaintenanceTicketRequest: {
      /** @enum {string} */
      status: "OPEN" | "RESOLVED";
    };
    MaintenanceTicket: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      leaseId?: string;
      /** Format: uuid */
      flatId?: string;
      /** Format: uuid */
      tenantId?: string;
      title?: string;
      description?: string;
      /** @enum {string} */
      status?: "OPEN" | "RESOLVED";
      /** Format: date-time */
      createdAt?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listLeases: {
    parameters: {
      query: {
        tenantId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Lease"][];
        };
      };
    };
  };
  getLease: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Lease"];
        };
      };
    };
  };
  listRentPayments: {
    parameters: {
      query: {
        leaseId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RentPayment"][];
        };
      };
    };
  };
  recordRentPayment: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecordRentPaymentRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RentPayment"];
        };
      };
    };
  };
  listMaintenanceTickets: {
    parameters: {
      query?: {
        tenantId?: string;
        leaseId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaintenanceTicket"][];
        };
      };
    };
  };
  createMaintenanceTicket: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMaintenanceTicketRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaintenanceTicket"];
        };
      };
    };
  };
  getMaintenanceTicket: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaintenanceTicket"];
        };
      };
    };
  };
  updateMaintenanceTicket: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMaintenanceTicketRequest"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MaintenanceTicket"];
        };
      };
    };
  };
}
