/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/wallets/{investorId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["listWallets"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/wallets/{investorId}/balance": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations["getAggregateBalance"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/wallets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["createCustodialWallet"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/wallets/link": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations["linkWallet"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    CreateCustodialWalletRequest: {
      /** Format: uuid */
      investorId?: string;
      label?: string;
    };
    LinkWalletRequest: {
      /** Format: uuid */
      investorId: string;
      walletAddress: string;
      label?: string;
      primary?: boolean;
    };
    Wallet: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      investorId?: string;
      walletAddress?: string;
      /** @enum {string} */
      walletType?: "CUSTODIAL" | "LINKED";
      label?: string | null;
      primary?: boolean;
    };
    AggregateBalance: {
      /** Format: uuid */
      investorId?: string;
      fiatBalanceUsd?: number;
      tokenHoldingsUsd?: number;
      totalBalanceUsd?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listWallets: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investorId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Wallet"][];
        };
      };
    };
  };
  getAggregateBalance: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        investorId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AggregateBalance"];
        };
      };
    };
  };
  createCustodialWallet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateCustodialWalletRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Wallet"];
        };
      };
    };
  };
  linkWallet: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LinkWalletRequest"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Wallet"];
        };
      };
    };
  };
}
