spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true

tokenrealty:
  payment:
    auto-confirm:
      enabled: false
    blockchain:
      deposit-watcher:
        enabled: false

logging:
  level:
    com.tokenrealty: INFO
